language: java
jdk:
  - oraclejdk8
script: mvn test --fail-at-end --batch-mode -Dmatsim.preferLocalDtds=true 
#-Dmaven.test.redirectTestOutputToFile
env:
  global:
    - export MAVEN_OPTS="-Xmx500m"


